# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Google I/O Extended Brasília
email: gdgbrasilia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A versão Extended 2016 do evento mundial direcionado a desenvolvedores de software acontecerá na capital em maio de 2016
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gdgbrasilia.github.io/io16extended" # the base hostname & protocol for your site
twitter_username: gdgbrasilia
github_username:  gdgbrasilia

# Build settings
markdown: kramdown
